baseurl      = "https://stupefied-bose-cb9c07.netlify.app/"
title        = "palabras"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
canonifyURLs = true
enableEmoji     = true

# googleAnalytics = ""
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false
# disqusShortname = "palabras-1"

[permalinks]
  posts = "/posts/:year/:month/:title/"


# Social icons
[[params.social]]
name = "twitter"
url  = "https://twitter.com/leiluspocus"

[[params.social]]
name = "github"
url  = "https://github.com/leiluspocus"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/lailatrmouh"

[[params.social]]
name = "stackoverflow"
url  = "https://www.stackoverflow.com/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Blog technique de Laïla ATRMOUH, développeuse fullstack"
  keywords = "homepage, blog"
  images = [""]
  
  [params.portrait]
    path = "https://placekitten.com/300/300"
    alt = "Cats"
    
  # Default theme "light" or "dark"
  defaultTheme = "light"

[author]
  name = "Laïla ATRMOUH"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hi there !"
    subtitle = "Thoughts and discoveries about our technical world today"
    homeSubtitle = "I'm Laïla, I'm a Software Engineer based in Paris, France. I love coding, learning and cute animals."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "palabras"
      logoHomeLink = "/" 

  [languages.fr]
    title = "Coucou !"
    subtitle = "Pensées et découvertes du monde du code aujourd'hui"
    homeSubtitle = "Je suis Laïla, je suis une développeuse web vivant à Paris. J'aime coder, apprendre et les animaux mignons."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Lire plus d'articles"

    [languages.fr.params.logo]
      logoText = "palabras"
      logoHomeLink = "/" 

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"